config/routes.rb
Rails.application.routes.draw do

  resources :notification_users, only: [:create]

  get 'users/beta_index'

  post 'points/add_watch_ttc_moive_points'

  # BEGIN Food Action Tracker routes
  get "food/:year/:month/:day" => "fat_meals#edit", as: 'fat_date'
  get "food" => "fat_meals#edit", as: 'fat'
  post "food" => "fat_meals#create"
  patch "food" => "fat_meals#update"
  # END Food Action Tracker routes

  resources :organizations do
    resources :users, only: [:create]
    member do
      post 'email_members_upload_file'
      post 'import_members_upload_file'
      post 'add_individual' #add_member
      get  'download_csv_template'
    end
  end

  # use routes error to handle both member and collection routes when exception is thrown
  resources :errors, only: [:user_error, :application_error, :not_found, :internal_server_error] do
     member do
      get 'user_error'
     end

     collection do
      get 'user_error'
     end
  end

  # exceptions and errors handling for application
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  match "/apperror", :to => "errors#application_error", :via => :all

  root 'pages#index'

  get 'domino-team' => 'pages#team'
  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  get 'privacy' => 'pages#privacy'
  get 'faq' => 'pages#faq'
  get 'example' => 'pages#example'
  get 'partners' => 'pages#partners'
  get 'challenges' => 'profiles#challenges'
  get 'member_benefits' => 'profiles#member_benefits'

  get '/welcome-email/:profile_id' => 'profiles#welcome_email'
  get '/legacy-user-registration-email/:lu_id' => 'profiles#lu_registration_email'
  get "/dashboard/:slug" => redirect{ |params, req| "users/sign_up?#{req.params.to_query}" }

  get "/continue/:profile_id" => 'pages#index'

  get "/newsletter-subscribe" => 'pages#newsletter_subscribe'

  ## BEGIN articles routes ##
  get "/articles/:id", to: 'posts#show', constraints: {id: /[0-9]+/}
  get "/articles/:article", to: 'posts#get_post_by_slug', as: 'post_slug'

  get 'myhome', to: redirect('/challenges')

  # for backward supports of old URLs
  get "/blog", to: redirect('/articles')

  # take care of get post by article slug
  get "/blog/:article",  to: redirect('/articles/%{article}')

  # take care of get posts by category
  get "/blog/category/:cat", to: redirect('/articles/?cat=%{cat}')

  resources :posts, :path => 'articles'

  get "/category/:cat", to: redirect('/articles?cat=%{cat}')
  ## END articles routes ##

  get '/dashboard' => 'dashboards#show', as: :user_dashboard
  resources :dashboards do
    patch 'bulk_update' => 'recommendations#bulk_update', as: 'bulk_update'
  end

  get '/profile/verify-current-password' => 'profiles#verify_current_password'  # XmlHttpRequest
  patch '/profile/update-password' => 'profiles#update_password'  # XmlHttpRequest
  get 'profile' => 'profiles#show', as: 'member_profile'
  get 'profile/welcome-tour-complete' => 'profiles#welcome_tour_complete' # XmlHttpRequest
  get 'profile/fat-intro-complete' => 'profiles#fat_intro_complete'  # XmlHttpRequest
  patch '/profile/update-notification' => 'profiles#update_notifications', as: 'update_notifications'

  resources :profiles, only: [:new, :update, :create, :show, :index] do
    resources :steps, only: [:show, :update], controller: 'profile/steps'
  end

  put '/profiles/:id/apply-partner-code' => 'profiles#apply_partner_code'
  post '/profiles/create-completed-profile' => 'profiles#create_completed_profile', as: 'create_completed_profile'

  # Devise routes
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  devise_scope :user do
    get ':org_name'  => "registrations#new_org_member", constraints: { org_name: /(sungevity|mydomino|test)/ }
    get 'pm'  => "registrations#new_member"

    get "check-org-member-email" => "registrations#check_org_member_email" # XMLHttpRequest
    post "create-org-member" => "registrations#create_org_member" # XMLHttpRequest
    patch "set-org-member-password" => "registrations#set_org_member_password" # XMLHttpRequest
  end


  resources :recommendations, only: [:destroy, :update, :index] do
    post 'complete'
    delete 'undo' => 'recommendations#undo', as: 'undo_complete'
  end

  resources :products do
    post 'toggle_default' => 'products#toggle_default'
  end
  post 'products/update-prices' => 'products#update_all_amazon_prices', as: 'update_product_prices'

  resources :tasks do
    post 'toggle_default' => 'tasks#toggle_default'
  end

  resource :analytics, only: [:show]

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  icon        :string
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  cta_link    :string
#  cta_text    :string
#  default     :boolean          default(FALSE)
#






class Task < ActiveRecord::Base
  has_many :recommendations, as: :recommendable, dependent: :destroy
  has_many :dashboards, through: :recommendations, source: :recommendable

  ICON_OPTIONS = ['energy', 'heat', 'vehicle']
  validates_inclusion_of :icon, :in => ICON_OPTIONS

  scope :default, -> { where(default: true) }


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action :authenticate_concierge!
  layout 'concierge'

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def index
    authorize Task
    @default_tasks = Task.where(default: true)
    @non_default_tasks = Task.where(default: false)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.delete
    redirect_to tasks_path
  end

  def toggle_default
    @task = Task.find(params[:task_id])
    @task.default = !@task.default
    @task.save
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :icon, :cta_link, :cta_text)
  end

end

app/views/tasks/_form.html.haml
=simple_form_for @task do |form|
  =form.label :name, class: 'bold' 
  =form.input_field :name, class: 'text-input'
  .mt1
    =form.label :description, class: 'bold'
    =form.input_field :description, class: 'text-input'
  .mt1
    =form.label :cta_link, class: 'bold'
    =form.input_field :cta_link, class: 'text-input'
  .mt1
    =form.label :cta_text, class: 'bold'
    =form.input_field :cta_link, class: 'text-input'
  .mt1
    =form.label :icon, class: 'block bold'
    =form.select :icon, {collection: Task::ICON_OPTIONS}, {}, {class: 'block select-box', style: 'width: 128px;'}
  .my2.block.right-align
    =form.submit local_assigns.fetch(:submit_text, "Add Action"), class: "btn btn-sm btn-primary"

app/views/tasks/_index_task.html.haml
.clearfix.flex.items-center.px2
  .col.sm-col-2.center
    %h3
      =link_to task_toggle_default_path(task.id), method: "POST", class: 'text-decoration-none blue' do
        -if (task.default)
          .fa.fa-check-square-o
        -else
          .fa.fa-square-o
        Default
  .col.sm-col-2
    =image_tag task.icon, width: "75px"
  .col.sm-col-5
    %h3.bold.mb0
      =task.name
    %h3.mt0
      =task.description
  .col.sm-col-3.center.hover-show
    =link_to "Edit", edit_task_path(task), class: 'btn btn-sm btn-primary'
    =link_to "Delete", task_path(task), class: 'btn btn-sm btn-secondary',  method: :delete, data: {confirm: 'Are you sure?'}

app/views/tasks/_task.html.haml
-cache(task.cache_key) do
  .pointer{data: {toggle: 'modal', target: "#task-#{task.id}"}}
    .center.py2
      =image_tag task.icon, style: 'max-height: 100px;'
    %h4.center.caps.bold.truncate
      =task.name
    .description{style: 'max-height: 90px;overflow: hidden;' }
      %p
        =task.description

app/views/tasks/_task_modal.html.haml
.clearfix.mx-auto.max-width-4.modal.fixed.top-0.bottom-0.left-0.right-0.fade{id: "task-#{task.id}"}
  .modal-dialog
    .modal-content.bg-white
      .modal-header.relative
        .absolute.top-0.left-0.close.pointer{"data-dismiss" => "modal"}
          .fa.fa-times.fa-2x.blue
      .modal-body
        .clearfix.max-width-4
          .sm-col.sm-col-12.md-col-6.center.py4
            =image_tag task.icon
          .sm-col.sm-col-12.md-col-6
            %h3
              =task.name
            %p
              =task.description

            -if(task.cta_link.present?)
              %p
                =link_to task.cta_text, task.cta_link, class: 'center btn btn-sm btn-primary px0 fill-x', style: 'background-color: #105585;'
            %p
              -if(!recommendation.done)
                =link_to "I've done this", recommendation_complete_path(recommendation.id), class: 'center btn btn-sm btn-primary px0 fill-x', method: "POST"
              -else
                =link_to "Mark as Incomplete", recommendation_undo_complete_path(recommendation.id), class: 'center btn btn-sm btn-primary px0 fill-x', method: "DELETE"

app/views/tasks/edit.html.haml
.clearfix.mx-auto.rounded.max-width-4.m2.bg-white
  %h1.center
    ="Edit #{@task.name}"
  .max-width-2.mx-auto
    =render 'form', submit_text: 'Update Action'

app/views/tasks/index.html.haml
.max-width-4.mx-auto.my4
  .clearfix.bg-white.px2
    .col.col-12
      %h1.mt0.inline-block.p2 Actions
  .clearfix.bg-white.px2
    -@default_tasks.each do |task|
      .clearfix
        .col.col-12
          =render 'tasks/index_task', task: task
    -@non_default_tasks.each do |task|
      .clearfix
        .col.col-12
          =render 'tasks/index_task', task: task

app/views/tasks/new.html.haml
.clearfix.mx-auto.rounded.max-width-4.m2.bg-white
  %h1.center
    ="Add New Action"
  .max-width-2.mx-auto
    =render 'form'