config/routes.rb
Rails.application.routes.draw do

  resources :notification_users, only: [:create]

  get 'users/beta_index'

  post 'points/add_watch_ttc_moive_points'

  # BEGIN Food Action Tracker routes
  get "food/:year/:month/:day" => "fat_meals#edit", as: 'fat_date'
  get "food" => "fat_meals#edit", as: 'fat'
  post "food" => "fat_meals#create"
  patch "food" => "fat_meals#update"
  # END Food Action Tracker routes

  resources :organizations do
    resources :users, only: [:create]
    member do
      post 'email_members_upload_file'
      post 'import_members_upload_file'
      post 'add_individual' #add_member
      get  'download_csv_template'
    end
  end

  # use routes error to handle both member and collection routes when exception is thrown
  resources :errors, only: [:user_error, :application_error, :not_found, :internal_server_error] do
     member do
      get 'user_error'
     end

     collection do
      get 'user_error'
     end
  end

  # exceptions and errors handling for application
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  match "/apperror", :to => "errors#application_error", :via => :all

  root 'pages#index'

  get 'domino-team' => 'pages#team'
  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  get 'privacy' => 'pages#privacy'
  get 'faq' => 'pages#faq'
  get 'example' => 'pages#example'
  get 'partners' => 'pages#partners'
  get 'challenges' => 'profiles#challenges'
  get 'member_benefits' => 'profiles#member_benefits'

  get '/welcome-email/:profile_id' => 'profiles#welcome_email'
  get '/legacy-user-registration-email/:lu_id' => 'profiles#lu_registration_email'
  get "/dashboard/:slug" => redirect{ |params, req| "users/sign_up?#{req.params.to_query}" }

  get "/continue/:profile_id" => 'pages#index'

  get "/newsletter-subscribe" => 'pages#newsletter_subscribe'

  ## BEGIN articles routes ##
  get "/articles/:id", to: 'posts#show', constraints: {id: /[0-9]+/}
  get "/articles/:article", to: 'posts#get_post_by_slug', as: 'post_slug'

  get 'myhome', to: redirect('/challenges')

  # for backward supports of old URLs
  get "/blog", to: redirect('/articles')

  # take care of get post by article slug
  get "/blog/:article",  to: redirect('/articles/%{article}')

  # take care of get posts by category
  get "/blog/category/:cat", to: redirect('/articles/?cat=%{cat}')

  resources :posts, :path => 'articles'

  get "/category/:cat", to: redirect('/articles?cat=%{cat}')
  ## END articles routes ##

  get '/dashboard' => 'dashboards#show', as: :user_dashboard
  resources :dashboards do
    patch 'bulk_update' => 'recommendations#bulk_update', as: 'bulk_update'
  end

  get '/profile/verify-current-password' => 'profiles#verify_current_password'  # XmlHttpRequest
  patch '/profile/update-password' => 'profiles#update_password'  # XmlHttpRequest
  get 'profile' => 'profiles#show', as: 'member_profile'
  get 'profile/welcome-tour-complete' => 'profiles#welcome_tour_complete' # XmlHttpRequest
  get 'profile/fat-intro-complete' => 'profiles#fat_intro_complete'  # XmlHttpRequest
  patch '/profile/update-notification' => 'profiles#update_notifications', as: 'update_notifications'

  resources :profiles, only: [:new, :update, :create, :show, :index] do
    resources :steps, only: [:show, :update], controller: 'profile/steps'
  end

  put '/profiles/:id/apply-partner-code' => 'profiles#apply_partner_code'
  post '/profiles/create-completed-profile' => 'profiles#create_completed_profile', as: 'create_completed_profile'

  # Devise routes
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  devise_scope :user do
    get ':org_name'  => "registrations#new_org_member", constraints: { org_name: /(sungevity|mydomino|test)/ }
    get 'pm'  => "registrations#new_member"

    get "check-org-member-email" => "registrations#check_org_member_email" # XMLHttpRequest
    post "create-org-member" => "registrations#create_org_member" # XMLHttpRequest
    patch "set-org-member-password" => "registrations#set_org_member_password" # XMLHttpRequest
  end


  resources :recommendations, only: [:destroy, :update, :index] do
    post 'complete'
    delete 'undo' => 'recommendations#undo', as: 'undo_complete'
  end

  resources :products do
    post 'toggle_default' => 'products#toggle_default'
  end
  post 'products/update-prices' => 'products#update_all_amazon_prices', as: 'update_product_prices'

  resources :tasks do
    post 'toggle_default' => 'tasks#toggle_default'
  end

  resource :analytics, only: [:show]

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id           :integer          not null, primary key
#  name         :string
#  email        :string
#  phone        :string
#  fax          :string
#  company_url  :string
#  sign_up_code :string
#  join_date    :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  users_count  :integer          default(0)
#  email_domain :string
#









class Organization < ActiveRecord::Base
	has_many :teams, dependent: :destroy
	has_many :users, dependent: :nullify
	has_many :subscriptions, dependent: :destroy

	validates :name, :email, :presence => true

  # equivalent to this but more portable between OS "#{Rails.root}/public/images/organization_logos"
	#LOGO_FULL_FILE_PATH = File.join "#{Rails.root}", "app", "assets", "images", "organization_logos" 
  LOGO_FULL_FILE_PATH = File.join "#{Rails.root}", "public", "images", "organization_logos" 
	LOGO_ASSETS_FILE_PATH = "organization_logos"



  #################################################################
  # 
  # Note about placing image files in Rails
  # If Rails can find the image in the asset folders, then it will link to the compiled asset path. 
  # If it can not find the image, it will link to the images folder under public instead
  # 
  # image_tag("logo.png") 
  # => '/assets/logo-f2c87c4e3fda671a619ccb7...png'  # if image exists
  # => '/images/logo.png'   # if image does not exists in asset folder


	def has_logo?

    return File.exists? logo_fullpath_filename
    
  end

  # return the Rails's assets pipeline path and file name of the organization logo
  def logo_path_name
    
    File.join LOGO_ASSETS_FILE_PATH, "#{self.name.downcase}_logo_400X400.png"

    # hmmm.... This does not work for image_tag
    #File.join "organization_logos", "#{self.name.downcase}_logo_400X400.png"

    #"organization_logos/#{self.name.downcase}_logo_400x400.png"

  end

  # return the full path and file name of the organization logo
	def logo_fullpath_filename

    File.join LOGO_FULL_FILE_PATH, "#{self.name.downcase}_logo_400X400.png"
  end

  # /get_leaderboard
  # Purpose: returns the organization's leaderboard
  def get_leaderboard
    users = self.users
    users.each do |u|
      u.point_log.get_points
    end
  end

  #########################################################################
  private
	

	
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  # Default password for individual members added via org admin dashboard
  DEFAULT_MEMBER_PASSWORD = 'ILoveCleanEnergy'

  before_action :set_organization, only: [:show, :add_individual, :email_members_upload_file, 
    :import_members_upload_file, :download_csv_template]

  before_action :authenticate_user!
  after_action :verify_authorized

  # GET /organizations/1
  def show
    authorize @organization
    
    # Empty user object for add indiviudal member form
    @user = User.new

    # Grab organization name to display on dashboard
    # Also, used for dynamically retrieving the company logo
    @organization_name = @organization.name

    # Grab email domain, to validate email domains client side
    # If no email domain exists, all domains are accepted when adding org members
    @organization_email_domain = @organization.email_domain
    if @organization_email_domain
      @email_regex = "[^]+@" + @organization_email_domain
    else
      @email_regex = "[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$"
    end
    
    # Member count is shown in the admin dashboard
    @member_count = @organization.users.size
  end

  # POST /organizations/1/add_individual
  # Purpose: Add member to organiztion via the org admin dashboard
  # Returns: JSON responses to client
  def add_individual
    authorize @organization

    # Form params
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:user][:email]

    # Create user record
    # Record is assigned the default pw
    # Record is associated with the organization
    @user = User.new(
      email: email,
      password: DEFAULT_MEMBER_PASSWORD,
      password_confirmation: DEFAULT_MEMBER_PASSWORD,
      organization: @organization
    )
    
    # If user record is valid (i.e record with provided email doesn't exist),
    # Provision Profile and Dashboard resources.
    if @user.save
      # Provision Dashboard
      @dashboard = Dashboard.create(
        lead_name: "#{first_name} #{last_name}", 
        lead_email: @user.email
      )

      @user.dashboard = @dashboard

      #Provision Profile
      @profile = Profile.create(
        first_name: first_name, 
        last_name: last_name, 
        email: @user.email, 
        user: @user
      )

      # Send updated member count back to view
      member_count = @organization.users.size
      
      render json: {
          message: "Member added successfully",
          member_count: member_count, 
          status: 200
        }, status: 200
      else
        render json: {
          error: "Email already taken",
          status: 400
        }, status: 400
    end

  end

  def email_members_upload_file
    authorize Organization

    # check to make sure the CSV file was selected
    if params[:file].nil?
      redirect_to @organization, alert: 'Error! Please select a CSV file to upload.' and return
    end

    # email the uploaded CSV file to mydomino
    UserMailer.email_csv_file(current_user, params[:file]).deliver_now
    
  end

  def import_members_upload_file
    authorize Organization
  end

  def download_csv_template
    authorize Organization
    send_data generate_csv_template, filename: "#{@organization.name}_#{Date.today}.csv"
  end

  private

  def set_organization
    @organization = Organization.find_by!(id: params[:id])
  end

  def generate_csv_template
    CSV.generate do |csv|
      # Add new headers
      csv << ['First_name', 'Last_name', 'Email']
    end
  end

end

app/views/organizations/_form.html.haml
= simple_form_for(@organization) do |f|
  = f.error_notification

  .form-inputs

    = f.input :name

    = f.input :email

    = f.input :phone

    = f.input :fax

    = f.input :company_url

    = f.input :sign_up_code

    = f.input :join_date


  .form-actions
    = f.button :submit

app/views/organizations/email_members_upload_file.html.haml
.max-width-4.mx-auto.bg-gray-1.my4
  .max-width-2.mx-auto.p4.line-height-2.gray-5
    %h1.mt0 Thank you for sending us your employees CSV file. 
    %h2.line-height-2
      Your request will be processed shortly. Please check back later.
    
    = link_to root_path do 
      .btn.btn-md.btn-primary.btn-primary--hover
        Back to home

app/views/organizations/show.html.haml
-content_for :meta do
  %meta{name: "turbolinks-cache-control", content:"no-cache"}

-content_for :body_class do
  bg-gray-1

/%p#notice= notice

.bg-gray-1
  .max-width-4.mx-auto.p2
    .flex.items-center
      .fill-black
        = inline_svg "icons/i-admin.svg", class:"icon-l"
      %h1.ml2 Admin

    .clearfix
      .max-width-1.bg-white.rounded.mb3.flex.content-center
        =image_tag "organization_logos/#{@organization_name.downcase}_logo_400x400.png", size: "64x64", class: "m2"

        /- if @organization.has_logo?
        /  =image_tag @organization.logo_path_name, size: "64x64", class: "m2"
        /- else
        /  No Logo.
        
        %div.my2
          %h2.m0= @organization_name
          %h4.m0.gray-5 
            Employees enrolled: 
            %span#member-count= @member_count


    .clearfix
      .col.col-12.sm-col.sm-col-6.sm-pl0.sm-pr2
        .bg-white.rounded.p3.mb2
          %h2.my0 Add multiple employees
          %h4.mb0 Step 1. Get the CSV template
          %p.mt0.gray-5 Download the sample spreadsheet. The first 3 columns: first name, last name, email address are mandatory.
          = form_tag download_csv_template_organization_path(@organization), method: :get do
            = button_tag "Download template", class: 'btn btn-outline gray-5 px2'

          %h4.mb0 Step 2. Upload your updated CSV
          %p.mt0.gray-5 After you've added new employees to your CSV file, upload it to add the employees to your account.
          = form_tag email_members_upload_file_organization_path(@organization), multipart: true do
            = file_field_tag "file", accept: 'text/csv', class: 'p0'
            = button_tag "Upload CSV", class: 'rounded btn btn-primary px2 mt2'
          .container
            - flash.each do |key, value|
              %div{:class => "alert alert-#{key}"}= value

      .col.col-12.sm-col.sm-col-6.sm-pl0.sm-pr2
        .bg-white.rounded.p3.mb2
          %h2.my0 Add an employee
          = simple_form_for @user, url: add_individual_organization_path, html: {class: 'new_user clearfix'} do |f|
            .col.col-12.sm-col.sm-col-6.px2.sm-pl0.sm-pr2
              %label.h6.mb0.gray-5{for: 'first_name'} First name
              = text_field_tag :first_name, nil, class: 'text-input', data: {"parsley-required": "true"}
            .col.col-12.sm-col.sm-col-6.px2.sm-pl0.sm-pr2
              %label.h6.mb0.gray-5{for: 'last_name'} Last name
              = text_field_tag :last_name, nil, class: 'text-input', data: {"parsley-required": "true"}
            .col.col-12.px2.sm-pl0.sm-pr2
              = f.input :email, input_html: {class: 'text-input', data: {"parsley-required": "true", "parsley-pattern": "#{@email_regex}", "parsley-pattern-message": "Must be company email"}}, label: "Email", label_html: {class: "h6 mb0 gray-5"}

          .px2.sm-px0.mt2
            .flex.items-center.flex-wrap
              #btn-add-employee.btn.btn-sm.btn-primary Add employee
              #msg-add-member.flex.items-center.green{style:'display:none'}
                .h4.ml0.sm-ml2.mr1 Employee added
                = inline_svg "icons/i-success.svg", class: 'icon-s'

:javascript
  modulejs.require('org_admin_dashboard')();