config/routes.rb
Rails.application.routes.draw do

  resources :notification_users, only: [:create]

  get 'users/beta_index'

  post 'points/add_watch_ttc_moive_points'

  # BEGIN Food Action Tracker routes
  get "food/:year/:month/:day" => "fat_meals#edit", as: 'fat_date'
  get "food" => "fat_meals#edit", as: 'fat'
  post "food" => "fat_meals#create"
  patch "food" => "fat_meals#update"
  # END Food Action Tracker routes

  resources :organizations do
    resources :users, only: [:create]
    member do
      post 'email_members_upload_file'
      post 'import_members_upload_file'
      post 'add_individual' #add_member
      get  'download_csv_template'
    end
  end

  # use routes error to handle both member and collection routes when exception is thrown
  resources :errors, only: [:user_error, :application_error, :not_found, :internal_server_error] do
     member do
      get 'user_error'
     end

     collection do
      get 'user_error'
     end
  end

  # exceptions and errors handling for application
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  match "/apperror", :to => "errors#application_error", :via => :all

  root 'pages#index'

  get 'domino-team' => 'pages#team'
  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  get 'privacy' => 'pages#privacy'
  get 'faq' => 'pages#faq'
  get 'example' => 'pages#example'
  get 'partners' => 'pages#partners'
  get 'challenges' => 'profiles#challenges'
  get 'member_benefits' => 'profiles#member_benefits'

  get '/welcome-email/:profile_id' => 'profiles#welcome_email'
  get '/legacy-user-registration-email/:lu_id' => 'profiles#lu_registration_email'
  get "/dashboard/:slug" => redirect{ |params, req| "users/sign_up?#{req.params.to_query}" }

  get "/continue/:profile_id" => 'pages#index'

  get "/newsletter-subscribe" => 'pages#newsletter_subscribe'

  ## BEGIN articles routes ##
  get "/articles/:id", to: 'posts#show', constraints: {id: /[0-9]+/}
  get "/articles/:article", to: 'posts#get_post_by_slug', as: 'post_slug'

  get 'myhome', to: redirect('/challenges')

  # for backward supports of old URLs
  get "/blog", to: redirect('/articles')

  # take care of get post by article slug
  get "/blog/:article",  to: redirect('/articles/%{article}')

  # take care of get posts by category
  get "/blog/category/:cat", to: redirect('/articles/?cat=%{cat}')

  resources :posts, :path => 'articles'

  get "/category/:cat", to: redirect('/articles?cat=%{cat}')
  ## END articles routes ##

  get '/dashboard' => 'dashboards#show', as: :user_dashboard
  resources :dashboards do
    patch 'bulk_update' => 'recommendations#bulk_update', as: 'bulk_update'
  end

  get '/profile/verify-current-password' => 'profiles#verify_current_password'  # XmlHttpRequest
  patch '/profile/update-password' => 'profiles#update_password'  # XmlHttpRequest
  get 'profile' => 'profiles#show', as: 'member_profile'
  get 'profile/welcome-tour-complete' => 'profiles#welcome_tour_complete' # XmlHttpRequest
  get 'profile/fat-intro-complete' => 'profiles#fat_intro_complete'  # XmlHttpRequest
  patch '/profile/update-notification' => 'profiles#update_notifications', as: 'update_notifications'

  resources :profiles, only: [:new, :update, :create, :show, :index] do
    resources :steps, only: [:show, :update], controller: 'profile/steps'
  end

  put '/profiles/:id/apply-partner-code' => 'profiles#apply_partner_code'
  post '/profiles/create-completed-profile' => 'profiles#create_completed_profile', as: 'create_completed_profile'

  # Devise routes
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  devise_scope :user do
    get ':org_name'  => "registrations#new_org_member", constraints: { org_name: /(sungevity|mydomino|test)/ }
    get 'pm'  => "registrations#new_member"

    get "check-org-member-email" => "registrations#check_org_member_email" # XMLHttpRequest
    post "create-org-member" => "registrations#create_org_member" # XMLHttpRequest
    patch "set-org-member-password" => "registrations#set_org_member_password" # XMLHttpRequest
  end


  resources :recommendations, only: [:destroy, :update, :index] do
    post 'complete'
    delete 'undo' => 'recommendations#undo', as: 'undo_complete'
  end

  resources :products do
    post 'toggle_default' => 'products#toggle_default'
  end
  post 'products/update-prices' => 'products#update_all_amazon_prices', as: 'update_product_prices'

  resources :tasks do
    post 'toggle_default' => 'tasks#toggle_default'
  end

  resource :analytics, only: [:show]

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  url         :string
#  product_id  :string
#  description :string
#  image_url   :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  price       :string
#  xml         :string
#  name        :string
#  default     :boolean          default(FALSE)
#







require 'retries'
class Product < ActiveRecord::Base
  has_many :recommendations, as: :recommendable, dependent: :destroy
  has_many :dashboards, through: :recommendations, source: :recommendable

  validates_format_of :url, :with => /amazon.com\/.*[dg]p\/(?:product\/)?(\w*)/, message: "Not a valid Amazon product URL"

  after_create :retrieve_amazon_details

  scope :default, -> { where(default: true) }

  #to be called by delayed job
  def update_amazon_price
    #retries in case of 503 due to server overloading
    response = with_retries(:max_tries => 5, :max_sleep_seconds => 2.0 ){ query_amazon_api product_id }

    #amazon api allows only 1 api request/sec
    sleep 1
    parsed_response = Nokogiri::XML(response.body)
    begin
      self.price = !parsed_response.at_css('Price FormattedPrice').nil? ? parsed_response.at_css('Price FormattedPrice').text : parsed_response.at_css('FormattedPrice').text
    rescue StandardError => error
      #todo 
      #if this exception is encountered, the product is currently unavailable
      puts "Error is caught in update_amazon price method! Error is #{e.message}"
    end
    self.save
  end

  private

  def retrieve_amazon_details
    product_id ||= extract_id_from_url
    response = query_amazon_api product_id
    parse_amazon_response response
  end

  def extract_id_from_url
    self.product_id = /amazon.com\/.*[dg]p\/(?:product\/)?(\w*)/.match(self.url)[1]
  end

  def query_amazon_api id
    request = Vacuum.new
    request.aws_access_key_id = ENV['AWS_ACCESS_KEY_ID']
    request.aws_secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    request.associate_tag = 'domino09d-20'
    response = request.item_lookup(
      query: {
        'ItemId' => id,
        'ResponseGroup' => 'Large,Offers'
      }
    )
    return response
  end

  def update_price
    
  end

  def parse_amazon_response response
    parsed_response = Nokogiri::XML(response.body)
    self.xml = response.body
    self.name = parsed_response.at_css("Title").content
    self.url = parsed_response.at_css("DetailPageURL").content
    self.image_url = parsed_response.at_css("LargeImage URL").content
    self.price = parsed_response.at_css("Price FormattedPrice").content
    self.save
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  layout 'concierge'

  def index
    authorize Product
    @default_products = Product.where(default: true)
    @non_default_products = Product.where(default: false)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(create_product_params)
    authorize @product

    if @product.save
      redirect_to edit_product_path @product
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    authorize @product
  end

  def update
    authorize Product
    @product = Product.find(params[:id])
    if @product.update_attributes(edit_product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def update_all_amazon_prices
    authorize Product
    UpdateAllAmazonPricesJob.perform_later
    redirect_to :products
  end

  def toggle_default
    @product = Product.find(params[:product_id])
    @product.default = !@product.default
    @product.save
    redirect_to products_path
  end

  def destroy
    authorize Product
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def create_product_params
    params.require(:product).permit(:product_id, :url)
  end

  def edit_product_params
    params.require(:product).permit(:name, :description)
  end
end

app/views/products/_edit_form.html.haml
=simple_form_for @product do |form|
  =form.label :product_id, class: 'bold'
  =form.text_field :product_id, disabled: true, class: 'mb2 text-input'
  =form.label :url, class: 'bold'
  =form.text_field :url, disabled: true, class: 'mb2 text-input'
  =form.label :name, class: 'bold'
  =form.text_field :name, class: 'mb2 text-input'
  =form.label :description, class: 'bold'
  =form.text_area :description, class: 'mb2 text-input'
  .my2.block.right-align
    =form.submit "Update Product", class: "btn btn-sm btn-primary"

app/views/products/_index_product.haml
.clearfix.rounded.flex.items-center.px2
  .col.sm-col-2.center
    %h3
      =link_to product_toggle_default_path(product.id), method: "POST", class: 'text-decoration-none blue' do
        -if (product.default)
          .fa.fa-check-square-o
        -else
          .fa.fa-square-o
        Default
  .col.sm-col-2
    =image_tag product.image_url, width: "150px"
  .col.sm-col-5
    %h3.bold
      =link_to product.name, product.url, class: 'text-decoration-none black', target: '_blank'
    %h3.mt0
      =product.price
  .col.sm-col-3.center.hover-show.max-width-2
    =link_to "Edit", edit_product_path(product), class: 'btn btn-sm btn-primary'
    =link_to "Delete", product_path(product), class: 'btn btn-sm btn-secondary',  method: :delete, data: {confirm: 'Are you sure?'}

app/views/products/_new_form.html.haml
=simple_form_for @product do |form|
  =form.label :url, "Product URL"
  =form.input_field :url, class: 'text-input'
  .my2.block.right-align
    =form.submit "Add Product", class: "btn btn-sm btn-primary"

app/views/products/_product.html.haml
-cache(product.cache_key) do
  .pointer{data: {toggle: 'modal', target: "#product-#{product.id}"}}
    %div.flex
      =image_tag product.image_url, style: 'max-height: 225px;margin: auto;'
    %h4.center.bold.truncate
      =product.name
    %h3.center
      =product.price  

app/views/products/_product_modal.html.haml
.clearfix.mx-auto.max-width-4.modal.fixed.top-0.bottom-0.left-0.right-0.fade{id: "product-#{product.id}"}
  .modal-dialog
    .modal-content.bg-white
      .modal-header.relative
        .absolute.top-0.left-0.close.pointer{"data-dismiss" => "modal"}
          .fa.fa-times.fa-2x.blue
      .modal-body
        .clearfix.max-width-4
          .sm-col.sm-col-12.md-col-6.center.py4
            =image_tag product.image_url, style: 'max-height: 256px; max-width: 256px;'
          .col.col-12.md-col-6
            %h3
              =product.name
            %p
              =product.description
            %p
              =link_to "#{product.price} on Amazon", product.url, class: 'center btn btn-sm btn-primary px0 fill-x', style: 'background-color: #105585;',  target: "_blank"
            %p
              -if(!recommendation.done)
                =link_to "I've bought this", recommendation_complete_path(recommendation.id), class: 'center btn btn-sm btn-primary px0 fill-x', method: :post
              -else
                =link_to "Mark as Unpurchased", recommendation_undo_complete_path(recommendation.id), class: 'center btn btn-sm btn-primary px0 fill-x', method: :delete

app/views/products/edit.html.haml
.clearfix.mx-auto.rounded.max-width-4.m4.bg-white
  .max-width-3.mx-auto
    %h1
      ="Edit #{@product.name}"
    .max-width-2.mx-auto
      =render 'edit_form'

app/views/products/index.html.haml
.max-width-4.mx-auto.my4
  .clearfix.bg-white.rounded-top.px2
    .col.col-12.flex.items-center
      %h1.p2 Products
      =link_to "Update Prices", update_product_prices_path, class: 'btn btn-sm btn-primary', method: 'post'
  .clearfix.bg-white.px2
    -@default_products.each do |product|
      .clearfix
        .col.col-12
          =render 'products/index_product', product: product
    -@non_default_products.each do |product|
      .clearfix
        .col.col-12
          =render 'products/index_product', product: product

app/views/products/new.html.haml
.clearfix.mx-auto.rounded.max-width-4.m2.bg-white
  %h1.center Add New Product
  .max-width-2.mx-auto
    =render 'new_form'

app/views/products/show.html.haml
.container
  .clearfix.bg-white.mt3.p2.mb4
    .sm-col.sm-col-12.md-col-6.center
      =image_tag @product.image_url
    .sm-col.sm-col-12.md-col-6
      %h3
        =@product.name
      %ul
        %li
          =@product.price
        %li
          =link_to "View on Amazon", @product.url