config/routes.rb
Rails.application.routes.draw do

  resources :notification_users, only: [:create]

  get 'users/beta_index'

  post 'points/add_watch_ttc_moive_points'

  # BEGIN Food Action Tracker routes
  get "food/:year/:month/:day" => "fat_meals#edit", as: 'fat_date'
  get "food" => "fat_meals#edit", as: 'fat'
  post "food" => "fat_meals#create"
  patch "food" => "fat_meals#update"
  # END Food Action Tracker routes

  resources :organizations do
    resources :users, only: [:create]
    member do
      post 'email_members_upload_file'
      post 'import_members_upload_file'
      post 'add_individual' #add_member
      get  'download_csv_template'
    end
  end

  # use routes error to handle both member and collection routes when exception is thrown
  resources :errors, only: [:user_error, :application_error, :not_found, :internal_server_error] do
     member do
      get 'user_error'
     end

     collection do
      get 'user_error'
     end
  end

  # exceptions and errors handling for application
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  match "/apperror", :to => "errors#application_error", :via => :all

  root 'pages#index'

  get 'domino-team' => 'pages#team'
  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  get 'privacy' => 'pages#privacy'
  get 'faq' => 'pages#faq'
  get 'example' => 'pages#example'
  get 'partners' => 'pages#partners'
  get 'challenges' => 'profiles#challenges'
  get 'member_benefits' => 'profiles#member_benefits'

  get '/welcome-email/:profile_id' => 'profiles#welcome_email'
  get '/legacy-user-registration-email/:lu_id' => 'profiles#lu_registration_email'
  get "/dashboard/:slug" => redirect{ |params, req| "users/sign_up?#{req.params.to_query}" }

  get "/continue/:profile_id" => 'pages#index'

  get "/newsletter-subscribe" => 'pages#newsletter_subscribe'

  ## BEGIN articles routes ##
  get "/articles/:id", to: 'posts#show', constraints: {id: /[0-9]+/}
  get "/articles/:article", to: 'posts#get_post_by_slug', as: 'post_slug'

  get 'myhome', to: redirect('/challenges')

  # for backward supports of old URLs
  get "/blog", to: redirect('/articles')

  # take care of get post by article slug
  get "/blog/:article",  to: redirect('/articles/%{article}')

  # take care of get posts by category
  get "/blog/category/:cat", to: redirect('/articles/?cat=%{cat}')

  resources :posts, :path => 'articles'

  get "/category/:cat", to: redirect('/articles?cat=%{cat}')
  ## END articles routes ##

  get '/dashboard' => 'dashboards#show', as: :user_dashboard
  resources :dashboards do
    patch 'bulk_update' => 'recommendations#bulk_update', as: 'bulk_update'
  end

  get '/profile/verify-current-password' => 'profiles#verify_current_password'  # XmlHttpRequest
  patch '/profile/update-password' => 'profiles#update_password'  # XmlHttpRequest
  get 'profile' => 'profiles#show', as: 'member_profile'
  get 'profile/welcome-tour-complete' => 'profiles#welcome_tour_complete' # XmlHttpRequest
  get 'profile/fat-intro-complete' => 'profiles#fat_intro_complete'  # XmlHttpRequest
  patch '/profile/update-notification' => 'profiles#update_notifications', as: 'update_notifications'

  resources :profiles, only: [:new, :update, :create, :show, :index] do
    resources :steps, only: [:show, :update], controller: 'profile/steps'
  end

  put '/profiles/:id/apply-partner-code' => 'profiles#apply_partner_code'
  post '/profiles/create-completed-profile' => 'profiles#create_completed_profile', as: 'create_completed_profile'

  # Devise routes
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  devise_scope :user do
    get ':org_name'  => "registrations#new_org_member", constraints: { org_name: /(sungevity|mydomino|test)/ }
    get 'pm'  => "registrations#new_member"

    get "check-org-member-email" => "registrations#check_org_member_email" # XMLHttpRequest
    post "create-org-member" => "registrations#create_org_member" # XMLHttpRequest
    patch "set-org-member-password" => "registrations#set_org_member_password" # XMLHttpRequest
  end


  resources :recommendations, only: [:destroy, :update, :index] do
    post 'complete'
    delete 'undo' => 'recommendations#undo', as: 'undo_complete'
  end

  resources :products do
    post 'toggle_default' => 'products#toggle_default'
  end
  post 'products/update-prices' => 'products#update_all_amazon_prices', as: 'update_product_prices'

  resources :tasks do
    post 'toggle_default' => 'tasks#toggle_default'
  end

  resource :analytics, only: [:show]

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
end

app/views/layouts/partials/_analytics.html.erb
<!-- GA -->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '<%= j(ENV["ga_tracking"]) %>', 'auto');
    ga('send', 'pageview');
</script>
<!-- Facebook Conversion Code for FB Leads - Domino -->
<script>(function() {
var _fbq = window._fbq || (window._fbq = []);
if (!_fbq.loaded) {
var fbds = document.createElement('script');
fbds.async = true;
fbds.src = '//connect.facebook.net/en_US/fbds.js';
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(fbds, s);
_fbq.loaded = true;
}
})();
window._fbq = window._fbq || [];
</script>
<!-- Google Adwords conversion tracking -->
<script type="text/javascript">
  /* <![CDATA[ */
  goog_snippet_vars = function() {
    var w = window;
    w.google_conversion_id = 908572511;
    w.google_conversion_label = "qkhKCIW8ql8Q3-6esQM";
    w.google_remarketing_only = false;
  }
  // DO NOT CHANGE THE CODE BELOW.
  goog_report_conversion = function(url) {
    goog_snippet_vars();
    window.google_conversion_format = "3";
    var opt = new Object();
    opt.onload_callback = function() {
    if (typeof(url) != 'undefined') {
      window.location = url;
    }
  }
  var conv_handler = window['google_trackConversion'];
  if (typeof(conv_handler) == 'function') {
    conv_handler(opt);
  }
}
/* ]]> */
</script>
<script type="text/javascript"
  src="//www.googleadservices.com/pagead/conversion_async.js">
</script>

<!-- Typekit -->
<script src="https://use.typekit.net/hif3ekt.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>
<!-- Adroll -->
<script type="text/javascript">
    adroll_adv_id = "4UF5H5OLSJCYDIENRYJ73O";
    adroll_pix_id = "7RBAPAA2AZHXFA5OMP5IAS";
    (function () {
        var _onload = function(){
            if (document.readyState && !/loaded|complete/.test(document.readyState)){setTimeout(_onload, 10);return}
            if (!window.__adroll_loaded){__adroll_loaded=true;setTimeout(_onload, 50);return}
            var scr = document.createElement("script");
            var host = (("https:" == document.location.protocol) ? "https://s.adroll.com" : "http://a.adroll.com");
            scr.setAttribute('async', 'true');
            scr.type = "text/javascript";
            scr.src = host + "/j/roundtrip.js";
            ((document.getElementsByTagName('head') || [null])[0] ||
                document.getElementsByTagName('script')[0].parentNode).appendChild(scr);
        };
        if (window.addEventListener) {window.addEventListener('load', _onload, false);}
        else {window.attachEvent('onload', _onload)}
    }());
</script>

app/views/layouts/partials/_crisp.html.erb
<!-- Crisp Code for user chat -->
<script type="text/javascript">
  window.$crisp=[];
  window.CRISP_WEBSITE_ID="a9ba6e9d-9e7e-433c-a7a8-87ec33965b27";
  (function(){
    d=document;
    s=d.createElement("script");
    s.src="https://client.crisp.im/l.js";
    s.async=1;d.getElementsByTagName("head")[0].appendChild(s);
  })();
</script>

app/views/layouts/partials/_footer.html.haml
%footer.bg-gray-1.line-height-4
  .clearfix.max-width-4.mx-auto.py2

    #social-icons.col.col-12.sm-col-6.md-col-3.p2
      = link_to 'https://www.facebook.com/ourdominoeffect', target:'_blank', class: 'text-decoration-none' do
        %i.pointer.gray-6.fa.fa-2x.fa-facebook-square.px1.blue--hover
      = link_to 'https://twitter.com/OurDominoEffect', target:'_blank', class: 'text-decoration-none' do
        %i.pointer.gray-6.fa.fa-2x.fa-twitter.px1.blue--hover
      = link_to 'https://www.instagram.com/mydomino/', target:'_blank', class: 'text-decoration-none' do
        %i.pointer.gray-6.fa.fa-2x.fa-instagram.px1.blue--hover

    .col.col-12.sm-col.sm-col-6.md-col-3.p2.gray-6
      .bold Who we are
      MyDomino is a concierge service that's helping people like you switch to clean energy and save money.

    .col.col-12.sm-col.sm-col-6.md-col-3.p2.gray-6
      = form_tag "/newsletter-subscribe", remote: true, method: :get do
        .bold.mb1
          Sign up for our newsletter
        %input#newsletter-email.bg-transparent.rounded.mt1.text-input.mb1{style: 'height: 2em', type: 'email', name: 'email', required: true}
        %input#newsletter-subscribe.btn.btn-sm.btn-primary.btn-primary--hover{type: 'submit', value: 'Sign up'}
        %br

        .col.col-12.sm-col.sm-col-6.md-col-3.p2.gray-6
          = link_to 'mailto:hello@mydomino.com', class: 'text-decoration-none gray-6 blue--hover' do
            %i.fa.fa-envelope
            hello@mydomino.com

  %hr.gray-6.max-width-4

  .clearfix.max-width-4.mx-auto.py1

    .sm-col.sm-col-12.md-col-6.px2
      .white
        = image_tag "mydomino_esc_horizontal", class: 'fit', width: '250px'
      %p.h5.mt1.gray-6
        344 20th Street, Suite 220
        %br
        Oakland, CA 94612

    .sm-col.sm-col-12.md-col-6
      .clearfix
        .col.col-4.right.px2.flex.flex-wrap.justify-around
          .flex.items-center
            =link_to "https://www.bcorporation.net/community/mydomino", target: '_blank' do
              = image_tag "b-corp.png", style: 'max-width: 64px;', class: 'mb1'
          .flex.items-center
            =link_to "https://www.bbb.org/greater-san-francisco/business-reviews/fuel-economizers/mydomino-inc-in-oakland-ca-537274", target: '_blank' do
              = image_tag "bbb-logo.svg", width: '75%', style: 'max-width: 128px; min-width: 100px'

        .col.col-4.right.px2
          %h4.gray-6.my0 COMPANY
          %ul.mt0.list-reset.h5
            %li
              = link_to "Blog", "http://blog.mydomino.com" , class: 'text-decoration-none gray-6 pointer blue--hover'
            %li
              = link_to "About Us", about_path, class: 'text-decoration-none gray-6 pointer blue--hover'
            %li
              = link_to "Partners", partners_path, class: 'text-decoration-none gray-6 pointer blue--hover'
            %li
              = link_to "Our Team", domino_team_path, class: 'text-decoration-none gray-6 pointer blue--hover'
            %li
              = link_to "Careers", "https://angel.co/mydomino/jobs", target: '_blank', class: 'text-decoration-none gray-6 pointer blue--hover'
            %li
              = link_to "Press", "http://mydomino.strikingly.com", target: '_blank', class: 'text-decoration-none gray-6 pointer blue--hover'

        .col.col-4.right.px2
          %h4.gray-6.my0 LEARN MORE
          %ul.mt0.list-reset.h5
            %li
              = link_to "Solar 101", post_slug_url('solar-101'), class: 'text-decoration-none gray-6 pointer blue--hover'
            %li
              = link_to "Can't Go Solar?", post_slug_url('cant-go-solar'), class: 'text-decoration-none gray-6 pointer blue--hover'
            %li
              = link_to "Get Efficient", post_slug_url('get-efficient'), class: 'text-decoration-none gray-6 pointer blue--hover'
            %li
              = link_to "Stay Warm, Be Cool", post_slug_url('stay-warm-cool'), class: 'text-decoration-none gray-6 pointer blue--hover'
            %li
              = link_to "Ride Electric", post_slug_url('ride-electric'), class: 'text-decoration-none gray-6 pointer blue--hover'
            %li
              = link_to "FAQ", faq_path, class: 'text-decoration-none gray-6 pointer blue--hover'

  %hr.gray-6.max-width-4
  .max-width-4.mx-auto.gray-6.h5.py1.px2
    &copy;&nbsp;
    = Date.today.year
    MyDomino Inc.
    = link_to 'Terms of Service', terms_path, class: 'text-decoration-none gray-6 mx1 pointer blue--hover'
    = link_to 'Privacy Policy', privacy_path, class: 'text-decoration-none gray-6 mx1 pointer blue--hover'
    CA&nbsp;CSLB&nbsp;1016806

app/views/layouts/partials/_logo_only_navbar.html.haml
%nav.clearfix
  .max-width-4.mx-auto
    .sm-col.sm-col-12.mt2.ml2
      = link_to embedded_svg('mydomino_logo_universal.svg'), root_path
      -if current_user.role == 'lead'
        =link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn-navbar gray-6 border p1 rounded text-decoration-none navbar-element right mt1'

app/views/layouts/partials/_meta.html.haml
%meta{name: 'google-site-verification', content: '5s_fZsv1gHwFzIdMwqyXngXqnTJolYGN-ZG70JJ8P3Q'}
%meta{'http-equiv' => 'Content-Type', content: 'text/html; charset=UTF-8'}
%meta{name: 'viewport', content: 'width=device-width, initial-scale=1'}
%meta{name: 'description', content: '100% clean energy is awesome. MyDomino makes it easy. From solar panels to smart thermostats and everything in between, we’ve done the research and lined up deals so you don’t have to.' }

// Default open graph meta tags shouldn't appear on blog articles
- if content_for? :post_og_meta
  = yield :post_og_meta
-else
  %meta{property: "og:type", content: "website"}
  %meta{property: "og:title", content: "MyDomino"}
  %meta{property: "og:image", content: "http://www.mydomino.com/assets/homepage-hero.jpg"}
  %meta{property: "og:description", content: '100% clean energy is awesome. MyDomino makes it easy. From solar panels to smart thermostats and everything in between, we’ve done the research and lined up deals so you don’t have to.'}
  %meta{property: "og:url", content: root_url}

// Page specific meta tags (i.e. Disabling turbolinks for a given page)
=yield :meta

app/views/layouts/partials/_navbar.html.haml
- homepage = current_page?(root_path)
- nav_element_color = "#{homepage ? 'white' : 'gray-5'}"

%header#header
  %nav#navbar.col-12.z3.top-0.pt2{class: "#{homepage ? 'absolute' : 'bg-white'}"}
    .max-width-4.mx-auto.flex.items-center.justify-between
      - org_member = current_user && !current_user.organization.nil?
      - private_beta_member = current_user && !current_user.group_users.find {|g| g.group.name == "beta"}.nil?

      = link_to (org_member || private_beta_member ? challenges_path : root_path), id: "navbar-brand", class: 'pl2' do
        = image_tag "mydomino_logo#{'_universal' if !homepage}.svg", id: 'logo', style: "#{'width: 128px;' if @browser.device.mobile?}"

      .xs-hide.sm-hide.my1.inline-block.col-10
        -if user_signed_in?
          .flex.justify-between
            .inline
              -if current_user.role == 'concierge'
                =link_to 'Concierge tools', dashboards_path, class: "#{nav_element_color} navbar-element btn-navbar border p1 rounded text-decoration-none navbar-element"

              -if (org_member || private_beta_member)
                = link_to challenges_path, class: 'text-decoration-none ml3 mr2' do
                  %span.inline-block.h5.blue--hover{class: "#{((current_page? '/challenges') || (request.fullpath.start_with? '/food')) ? 'fill-blue blue' : nav_element_color}"}
                    = inline_svg "icons/i-challenge.svg", class:"block mx-auto", size:"32px * 22px"
                    Challenges
              -else
                = link_to user_dashboard_path, class: 'text-decoration-none mr2' do
                  %span.inline-block.h5.blue--hover{class: "#{(request.fullpath.start_with? '/dashboard') ? 'fill-blue blue mx1' : nav_element_color}"}
                    = inline_svg "icons/i-dashboard-nav.svg", class:"block mx-auto", size:"32px * 22px"
                    Dashboard

              = link_to "/articles", class: 'text-decoration-none mr2' do
                %span.inline-block.h5.blue--hover{class: "#{(request.fullpath.start_with? '/articles') ? 'fill-blue blue' : nav_element_color}"}
                  = inline_svg "icons/i-articles.svg", class:"icon-m block mx-auto"
                  Articles
              = link_to member_benefits_path, class: 'text-decoration-none mr2' do
                %span.inline-block.h5.blue--hover{class: "#{(current_page? '/member_benefits') ? 'fill-blue blue' : nav_element_color}"}
                  = inline_svg "icons/i-benefits.svg", class:"icon-m block mx-auto"
                  Benefits

            .inline.pr2
              = link_to member_profile_path, class: 'text-decoration-none mr1' do
                %span.inline-block.h5.blue--hover{class: "#{(current_page? '/profile') ? 'fill-blue blue' : nav_element_color}"}
                  = inline_svg "icons/i-user.svg", class:"icon-m block mx-auto"
                  Profile
              -if current_user.role == 'org_admin' && current_user.organization != nil
                = link_to organization_path(current_user.organization), class: 'text-decoration-none' do
                  %span.inline-block.mr2.h5.blue--hover{class: "#{(current_page? organization_path(current_user.organization)) ? 'fill-blue blue' : nav_element_color}"}
                    = inline_svg "icons/i-admin.svg", class:"icon-m block mx-auto"
                    Admin
              = link_to destroy_user_session_path, method: :delete, class: 'text-decoration-none' do
                %span.inline-block.h5.blue--hover{class: "#{nav_element_color}"}
                  = inline_svg "icons/i-logout.svg", class:"icon-m block mx-auto"
                  Logout

        -else
          .flex.items-center.right
            =link_to "Log in", new_user_session_path, class: "#{nav_element_color} navbar-element btn-navbar border py1 px2 rounded text-decoration-none right", id: "link-login"
            .h4.mx2.inline.navbar-element.right{class: "#{nav_element_color}"}


      .md-hide.lg-hide.px2.right
        %span#open-nav
          =embedded_svg 'icons/i-hamburger.svg', class:"#{nav_element_color} pointer navbar-element py2 pl3"

    .max-width-4.mx-auto.clearfix
      .col.col-12.h3.sm-hide.xs-hide
        = yield :posts_menu

  / Mobile & small viewport navigation menu
  #nav-overlay.overflow-scroll
    #nav-overlay-content
      %span#close-nav
        = embedded_svg 'i-close.svg', class:"white pointer absolute top-0 right-0 py3 pl3 pr2"

      .h1.p2.center.mt4
        = yield :posts_menu

      %ul.mt2.center.list-reset
        -if !user_signed_in?
          %li.h1
            = link_to 'Log in', new_user_session_path , class: "white py1 inline-block text-decoration-none"

        -else
          -if (org_member || private_beta_member)
            %li.h1
              =link_to 'Challenges', challenges_path, class: "white py1 inline-block text-decoration-none"
            %li.h1
              =link_to 'Articles', '/articles', class: "white py1 inline-block text-decoration-none"
            %li.h1
              =link_to 'Member Benefits', member_benefits_path, class: "white py1 inline-block text-decoration-none"
            -if current_user.role == 'org_admin' && current_user.organization != nil
              %li.h1
                =link_to 'Admin', organization_path(current_user.organization), class: "white py1 inline-block text-decoration-none"
          -else
            %li.h1
              = link_to 'Dashboard', user_dashboard_path, class: "white py1 inline-block text-decoration-none"
          %li.h1
            =link_to 'Profile', member_profile_path, class: "white py1 inline-block text-decoration-none"



          %li.h1
            = link_to 'Log out', destroy_user_session_path, method: :delete, class: "white py1 inline-block text-decoration-none"

:javascript
  (function(){
    var $nav = $('#nav-overlay');
    var $navContent = $('#nav-overlay-content');
    var $openNav = $('#open-nav');
    var $closeNav = $('#close-nav');
    var $body = $('body');


    var openNav = function(){
      $body.addClass('lock-position');
      $nav.css('z-index', '10');
      $nav.addClass('open');
    };

    var closeNav = function(){
      $body.removeClass('lock-position');
      $nav.removeClass('open');
      window.setTimeout( function(){ $nav.css('z-index', '0'); }, 500);
    };

    $openNav.on('click', openNav);
    $closeNav.on('click', closeNav);

  }());

app/views/layouts/partials/_posts_menu.html.haml
%ul.list-reset.md-flex.flex-row.mt3.mb0.sm-mt0.sm-mb3.sm-ml2
  %li.block.light
    = link_to "All", posts_path(), class: 'pr0 sm-pr4 text-decoration-none gray-6 white--hover sm-blue--hover'
  %li.block.light
    = link_to "Good Eats", posts_path(cat: "good-eats"), class: 'pr0 sm-pr4 text-decoration-none white--hover gray-6 sm-blue--hover'
  %li.block.light
    = link_to "Clean Power", posts_path(cat: "clean-power"), class: 'pr0 sm-pr4 text-decoration-none white--hover gray-6 sm-blue--hover'
  %li.block.light
    = link_to "Energy Efficiency", posts_path(cat: "energy-efficiency"), class: 'pr0 sm-pr4 text-decoration-none white--hover gray-6 sm-blue--hover'
  %li.block.light
    = link_to "Getting Around", posts_path(cat: "getting-around"), class: 'pr0 sm-pr4 text-decoration-none white--hover gray-6 sm-blue--hover'
  %li.block.light.sm-pr2
    = link_to "Buyer Guides", posts_path(cat: "buyer-guides"), class: 'pr0 sm-pr4 text-decoration-none white--hover gray-6 sm-blue--hover'